# .scrutinizer.yml

checks:
    php:
        code_rating: true
        duplication: true
build:
    image: default-bionic
    environment:
        php: 8.3
    tests:
        override:
            -
                command: 'bin/phpunit --coverage-clover=.coverage'
                coverage:
                    file: '.coverage'
                    format: 'clover'